# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'databaseconnection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_databaseForm(object):
    def setupUi(self, databaseForm):
        databaseForm.setObjectName("databaseForm")
        databaseForm.resize(210, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        databaseForm.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(databaseForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(databaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.hostNamelineEdit = QtWidgets.QLineEdit(databaseForm)
        self.hostNamelineEdit.setObjectName("hostNamelineEdit")
        self.verticalLayout.addWidget(self.hostNamelineEdit)
        self.label_2 = QtWidgets.QLabel(databaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.usernameLineEdit = QtWidgets.QLineEdit(databaseForm)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.label_3 = QtWidgets.QLabel(databaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.passwordLineEdit = QtWidgets.QLineEdit(databaseForm)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testConnectionpushButton = QtWidgets.QPushButton(databaseForm)
        self.testConnectionpushButton.setObjectName("testConnectionpushButton")
        self.horizontalLayout.addWidget(self.testConnectionpushButton)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.connectionLed = QtWidgets.QPushButton(databaseForm)
        self.connectionLed.setEnabled(False)
        self.connectionLed.setMaximumSize(QtCore.QSize(16, 16))
        self.connectionLed.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.connectionLed.setText("")
        self.connectionLed.setObjectName("connectionLed")
        self.horizontalLayout.addWidget(self.connectionLed)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(databaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.databaseNamecomboBox = QtWidgets.QComboBox(databaseForm)
        self.databaseNamecomboBox.setObjectName("databaseNamecomboBox")
        self.verticalLayout.addWidget(self.databaseNamecomboBox)
        self.label_5 = QtWidgets.QLabel(databaseForm)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.tableNamecomboBox = QtWidgets.QComboBox(databaseForm)
        self.tableNamecomboBox.setObjectName("tableNamecomboBox")
        self.verticalLayout.addWidget(self.tableNamecomboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.connectpushButton = QtWidgets.QPushButton(databaseForm)
        self.connectpushButton.setObjectName("connectpushButton")
        self.verticalLayout.addWidget(self.connectpushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(databaseForm)
        QtCore.QMetaObject.connectSlotsByName(databaseForm)

    def retranslateUi(self, databaseForm):
        _translate = QtCore.QCoreApplication.translate
        databaseForm.setWindowTitle(_translate("databaseForm", "Database Connection"))
        self.label_4.setText(_translate("databaseForm", "Host Name"))
        self.label_2.setText(_translate("databaseForm", "Username"))
        self.label_3.setText(_translate("databaseForm", "Password"))
        self.testConnectionpushButton.setText(_translate("databaseForm", "Test"))
        self.label.setText(_translate("databaseForm", "Database Name"))
        self.label_5.setText(_translate("databaseForm", "Table Name"))
        self.connectpushButton.setText(_translate("databaseForm", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    databaseForm = QtWidgets.QWidget()
    ui = Ui_databaseForm()
    ui.setupUi(databaseForm)
    databaseForm.show()
    sys.exit(app.exec_())
