# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(940, 660)
        HomeWindow.setMaximumSize(QtCore.QSize(940, 660))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons/monitor.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HomeWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        HomeWindow.setCentralWidget(self.centralwidget)
        self.actionSerial = QtWidgets.QAction(HomeWindow)
        self.actionSerial.setCheckable(False)
        self.actionSerial.setObjectName("actionSerial")
        self.actionConnect = QtWidgets.QAction(HomeWindow)
        self.actionConnect.setCheckable(False)
        self.actionConnect.setObjectName("actionConnect")
        self.actionMonitor = QtWidgets.QAction(HomeWindow)
        self.actionMonitor.setObjectName("actionMonitor")
        self.actionDatabase = QtWidgets.QAction(HomeWindow)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionRwDevice = QtWidgets.QAction(HomeWindow)
        self.actionRwDevice.setObjectName("actionRwDevice")
        self.actionUploader = QtWidgets.QAction(HomeWindow)
        self.actionUploader.setObjectName("actionUploader")

        self.retranslateUi(HomeWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "BMS"))
        self.actionSerial.setText(_translate("HomeWindow", "Serial Option"))
        self.actionConnect.setText(_translate("HomeWindow", "Connect"))
        self.actionMonitor.setText(_translate("HomeWindow", "Monitor"))
        self.actionDatabase.setText(_translate("HomeWindow", "Database"))
        self.actionRwDevice.setText(_translate("HomeWindow", "R/W Device"))
        self.actionUploader.setText(_translate("HomeWindow", "Uploader"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
