# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowTest(object):
    def setupUi(self, MainWindowTest):
        MainWindowTest.setObjectName("MainWindowTest")
        MainWindowTest.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowTest)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindowTest.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowTest)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindowTest)

    def retranslateUi(self, MainWindowTest):
        _translate = QtCore.QCoreApplication.translate
        MainWindowTest.setWindowTitle(_translate("MainWindowTest", "MainWindowTest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowTest = QtWidgets.QMainWindow()
    ui = Ui_MainWindowTest()
    ui.setupUi(MainWindowTest)
    MainWindowTest.show()
    sys.exit(app.exec_())
