# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maininfowindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainInfoWindow(object):
    def setupUi(self, MainInfoWindow):
        MainInfoWindow.setObjectName("MainInfoWindow")
        MainInfoWindow.resize(892, 670)
        MainInfoWindow.setMaximumSize(QtCore.QSize(900, 670))
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainInfoWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(MainInfoWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pack8 = QtWidgets.QPushButton(self.frame_2)
        self.pack8.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pack8.setIcon(icon)
        self.pack8.setIconSize(QtCore.QSize(60, 60))
        self.pack8.setDefault(False)
        self.pack8.setFlat(False)
        self.pack8.setObjectName("pack8")
        self.gridLayout.addWidget(self.pack8, 1, 1, 1, 1)
        self.pack2 = QtWidgets.QPushButton(self.frame_2)
        self.pack2.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack2.setText("")
        self.pack2.setIcon(icon)
        self.pack2.setIconSize(QtCore.QSize(60, 60))
        self.pack2.setDefault(False)
        self.pack2.setFlat(False)
        self.pack2.setObjectName("pack2")
        self.gridLayout.addWidget(self.pack2, 7, 1, 1, 1)
        self.pack7 = QtWidgets.QPushButton(self.frame_2)
        self.pack7.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack7.setText("")
        self.pack7.setIcon(icon)
        self.pack7.setIconSize(QtCore.QSize(60, 60))
        self.pack7.setDefault(False)
        self.pack7.setFlat(False)
        self.pack7.setObjectName("pack7")
        self.gridLayout.addWidget(self.pack7, 2, 1, 1, 1)
        self.pack6 = QtWidgets.QPushButton(self.frame_2)
        self.pack6.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack6.setText("")
        self.pack6.setIcon(icon)
        self.pack6.setIconSize(QtCore.QSize(60, 60))
        self.pack6.setDefault(False)
        self.pack6.setFlat(False)
        self.pack6.setObjectName("pack6")
        self.gridLayout.addWidget(self.pack6, 3, 1, 1, 1)
        self.pack5 = QtWidgets.QPushButton(self.frame_2)
        self.pack5.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack5.setText("")
        self.pack5.setIcon(icon)
        self.pack5.setIconSize(QtCore.QSize(60, 60))
        self.pack5.setDefault(False)
        self.pack5.setFlat(False)
        self.pack5.setObjectName("pack5")
        self.gridLayout.addWidget(self.pack5, 4, 1, 1, 1)
        self.packstatus4 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus4.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus4.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus4.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus4.setText("")
        self.packstatus4.setFlat(False)
        self.packstatus4.setObjectName("packstatus4")
        self.gridLayout.addWidget(self.packstatus4, 5, 0, 1, 1)
        self.pack1 = QtWidgets.QPushButton(self.frame_2)
        self.pack1.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack1.setText("")
        self.pack1.setIcon(icon)
        self.pack1.setIconSize(QtCore.QSize(60, 60))
        self.pack1.setDefault(False)
        self.pack1.setFlat(False)
        self.pack1.setObjectName("pack1")
        self.gridLayout.addWidget(self.pack1, 8, 1, 1, 1)
        self.packstatus3 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus3.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus3.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus3.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus3.setText("")
        self.packstatus3.setFlat(False)
        self.packstatus3.setObjectName("packstatus3")
        self.gridLayout.addWidget(self.packstatus3, 6, 0, 1, 1)
        self.packstatus1 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus1.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus1.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus1.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus1.setText("")
        self.packstatus1.setFlat(False)
        self.packstatus1.setObjectName("packstatus1")
        self.gridLayout.addWidget(self.packstatus1, 8, 0, 1, 1)
        self.packstatus2 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus2.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus2.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus2.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus2.setText("")
        self.packstatus2.setFlat(False)
        self.packstatus2.setObjectName("packstatus2")
        self.gridLayout.addWidget(self.packstatus2, 7, 0, 1, 1)
        self.packstatus6 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus6.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus6.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus6.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus6.setText("")
        self.packstatus6.setFlat(False)
        self.packstatus6.setObjectName("packstatus6")
        self.gridLayout.addWidget(self.packstatus6, 3, 0, 1, 1)
        self.packstatus7 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus7.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus7.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus7.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus7.setText("")
        self.packstatus7.setFlat(False)
        self.packstatus7.setObjectName("packstatus7")
        self.gridLayout.addWidget(self.packstatus7, 2, 0, 1, 1)
        self.packstatus8 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus8.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus8.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus8.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus8.setText("")
        self.packstatus8.setFlat(False)
        self.packstatus8.setObjectName("packstatus8")
        self.gridLayout.addWidget(self.packstatus8, 1, 0, 1, 1)
        self.pack4 = QtWidgets.QPushButton(self.frame_2)
        self.pack4.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack4.setText("")
        self.pack4.setIcon(icon)
        self.pack4.setIconSize(QtCore.QSize(60, 60))
        self.pack4.setDefault(False)
        self.pack4.setFlat(False)
        self.pack4.setObjectName("pack4")
        self.gridLayout.addWidget(self.pack4, 5, 1, 1, 1)
        self.pack3 = QtWidgets.QPushButton(self.frame_2)
        self.pack3.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pack3.setText("")
        self.pack3.setIcon(icon)
        self.pack3.setIconSize(QtCore.QSize(60, 60))
        self.pack3.setDefault(False)
        self.pack3.setFlat(False)
        self.pack3.setObjectName("pack3")
        self.gridLayout.addWidget(self.pack3, 6, 1, 1, 1)
        self.packstatus5 = QtWidgets.QPushButton(self.frame_2)
        self.packstatus5.setMinimumSize(QtCore.QSize(16, 16))
        self.packstatus5.setMaximumSize(QtCore.QSize(16, 16))
        self.packstatus5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packstatus5.setStyleSheet("QPushButton{\n"
"    border-radius : 8px;\n"
"    background-color: rgb(34, 34, 34);\n"
"}")
        self.packstatus5.setText("")
        self.packstatus5.setFlat(False)
        self.packstatus5.setObjectName("packstatus5")
        self.gridLayout.addWidget(self.packstatus5, 4, 0, 1, 1)
        self.rms = QtWidgets.QPushButton(self.frame_2)
        self.rms.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.rms.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/wifi-router.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rms.setIcon(icon1)
        self.rms.setIconSize(QtCore.QSize(60, 60))
        self.rms.setObjectName("rms")
        self.gridLayout.addWidget(self.rms, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.gridLayout.setRowStretch(6, 1)
        self.gridLayout.setRowStretch(7, 1)
        self.gridLayout.setRowStretch(8, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.ipAddressLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.ipAddressLineEdit.setEnabled(True)
        self.ipAddressLineEdit.setReadOnly(True)
        self.ipAddressLineEdit.setObjectName("ipAddressLineEdit")
        self.verticalLayout_3.addWidget(self.ipAddressLineEdit)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.framelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.framelineEdit.setEnabled(True)
        self.framelineEdit.setReadOnly(True)
        self.framelineEdit.setObjectName("framelineEdit")
        self.verticalLayout_3.addWidget(self.framelineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.cmscodelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.cmscodelineEdit.setReadOnly(True)
        self.cmscodelineEdit.setObjectName("cmscodelineEdit")
        self.verticalLayout_3.addWidget(self.cmscodelineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.basecodelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.basecodelineEdit.setReadOnly(True)
        self.basecodelineEdit.setObjectName("basecodelineEdit")
        self.verticalLayout_3.addWidget(self.basecodelineEdit)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.mcucodelineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.mcucodelineEdit.setReadOnly(True)
        self.mcucodelineEdit.setObjectName("mcucodelineEdit")
        self.verticalLayout_3.addWidget(self.mcucodelineEdit)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.sitelocationlineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.sitelocationlineEdit.setReadOnly(True)
        self.sitelocationlineEdit.setObjectName("sitelocationlineEdit")
        self.verticalLayout_3.addWidget(self.sitelocationlineEdit)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.bidlineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.bidlineEdit.setStyleSheet("")
        self.bidlineEdit.setReadOnly(True)
        self.bidlineEdit.setObjectName("bidlineEdit")
        self.verticalLayout_3.addWidget(self.bidlineEdit)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.statuslineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.statuslineEdit.setReadOnly(True)
        self.statuslineEdit.setObjectName("statuslineEdit")
        self.verticalLayout_3.addWidget(self.statuslineEdit)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.doorlineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.doorlineEdit.setReadOnly(True)
        self.doorlineEdit.setObjectName("doorlineEdit")
        self.verticalLayout_3.addWidget(self.doorlineEdit)
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.packVoltage = QtWidgets.QLCDNumber(self.frame_3)
        self.packVoltage.setAutoFillBackground(True)
        self.packVoltage.setFrameShape(QtWidgets.QFrame.Box)
        self.packVoltage.setSmallDecimalPoint(False)
        self.packVoltage.setDigitCount(5)
        self.packVoltage.setProperty("value", 0.0)
        self.packVoltage.setProperty("intValue", 0)
        self.packVoltage.setObjectName("packVoltage")
        self.horizontalLayout_4.addWidget(self.packVoltage)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.packContent = QtWidgets.QLCDNumber(self.frame_3)
        self.packContent.setAutoFillBackground(True)
        self.packContent.setFrameShape(QtWidgets.QFrame.Box)
        self.packContent.setSmallDecimalPoint(False)
        self.packContent.setDigitCount(5)
        self.packContent.setProperty("value", 0.0)
        self.packContent.setProperty("intValue", 0)
        self.packContent.setObjectName("packContent")
        self.horizontalLayout_5.addWidget(self.packContent)
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5.setStretch(0, 6)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 1)
        self.verticalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.setStretch(7, 1)
        self.verticalLayout_3.setStretch(8, 1)
        self.verticalLayout_3.setStretch(9, 1)
        self.verticalLayout_3.setStretch(10, 1)
        self.verticalLayout_3.setStretch(11, 1)
        self.verticalLayout_3.setStretch(12, 1)
        self.verticalLayout_3.setStretch(13, 1)
        self.verticalLayout_3.setStretch(14, 1)
        self.verticalLayout_3.setStretch(15, 1)
        self.verticalLayout_3.setStretch(16, 1)
        self.verticalLayout_3.setStretch(17, 1)
        self.verticalLayout_3.setStretch(18, 1)
        self.verticalLayout_3.setStretch(19, 2)
        self.verticalLayout_3.setStretch(21, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.charger = QtWidgets.QPushButton(self.frame_7)
        self.charger.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.charger.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/icons/charger-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.charger.setIcon(icon2)
        self.charger.setIconSize(QtCore.QSize(128, 128))
        self.charger.setFlat(False)
        self.charger.setObjectName("charger")
        self.verticalLayout_6.addWidget(self.charger, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bidirectionalinverter = QtWidgets.QPushButton(self.frame_8)
        self.bidirectionalinverter.setStyleSheet("QPushButton {\n"
"    border : none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(229, 241, 251);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.bidirectionalinverter.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/icons/solar-inverter-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bidirectionalinverter.setIcon(icon3)
        self.bidirectionalinverter.setIconSize(QtCore.QSize(128, 128))
        self.bidirectionalinverter.setObjectName("bidirectionalinverter")
        self.verticalLayout_7.addWidget(self.bidirectionalinverter, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 2, 1, 1)
        self.chargerCurrent = QtWidgets.QLCDNumber(self.frame_9)
        self.chargerCurrent.setAutoFillBackground(True)
        self.chargerCurrent.setDigitCount(4)
        self.chargerCurrent.setObjectName("chargerCurrent")
        self.gridLayout_2.addWidget(self.chargerCurrent, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 3, 1, 1, 1)
        self.chargerVoltage = QtWidgets.QLCDNumber(self.frame_9)
        self.chargerVoltage.setAutoFillBackground(True)
        self.chargerVoltage.setDigitCount(4)
        self.chargerVoltage.setObjectName("chargerVoltage")
        self.gridLayout_2.addWidget(self.chargerVoltage, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.chargerPower = QtWidgets.QLCDNumber(self.frame_9)
        self.chargerPower.setAutoFillBackground(True)
        self.chargerPower.setDigitCount(4)
        self.chargerPower.setObjectName("chargerPower")
        self.gridLayout_2.addWidget(self.chargerPower, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 5, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 6)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem7, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.bdiPower = QtWidgets.QLCDNumber(self.frame_12)
        self.bdiPower.setAutoFillBackground(True)
        self.bdiPower.setDigitCount(4)
        self.bdiPower.setObjectName("bdiPower")
        self.gridLayout_3.addWidget(self.bdiPower, 4, 1, 1, 1)
        self.bdiCurrent = QtWidgets.QLCDNumber(self.frame_12)
        self.bdiCurrent.setAutoFillBackground(True)
        self.bdiCurrent.setDigitCount(4)
        self.bdiCurrent.setObjectName("bdiCurrent")
        self.gridLayout_3.addWidget(self.bdiCurrent, 2, 1, 1, 1)
        self.bdiVoltage = QtWidgets.QLCDNumber(self.frame_12)
        self.bdiVoltage.setAutoFillBackground(True)
        self.bdiVoltage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bdiVoltage.setDigitCount(4)
        self.bdiVoltage.setProperty("value", 0.0)
        self.bdiVoltage.setObjectName("bdiVoltage")
        self.gridLayout_3.addWidget(self.bdiVoltage, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem8, 5, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 6)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(MainInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(MainInfoWindow)

    def retranslateUi(self, MainInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        MainInfoWindow.setWindowTitle(_translate("MainInfoWindow", "Form"))
        self.label_23.setText(_translate("MainInfoWindow", "IP Address"))
        self.label.setText(_translate("MainInfoWindow", "Frame Name"))
        self.label_2.setText(_translate("MainInfoWindow", "CMS Code"))
        self.label_3.setText(_translate("MainInfoWindow", "Base Code"))
        self.label_4.setText(_translate("MainInfoWindow", "Mcu Code"))
        self.label_5.setText(_translate("MainInfoWindow", "Site Location"))
        self.label_6.setText(_translate("MainInfoWindow", "Bid"))
        self.label_7.setText(_translate("MainInfoWindow", "Status"))
        self.label_8.setText(_translate("MainInfoWindow", "Door"))
        self.label_21.setText(_translate("MainInfoWindow", "Pack Voltage"))
        self.label_22.setText(_translate("MainInfoWindow", "Volts"))
        self.label_24.setText(_translate("MainInfoWindow", "Content"))
        self.label_25.setText(_translate("MainInfoWindow", "%    "))
        self.label_10.setText(_translate("MainInfoWindow", "Current"))
        self.label_12.setText(_translate("MainInfoWindow", "Volts"))
        self.label_14.setText(_translate("MainInfoWindow", "KW"))
        self.label_13.setText(_translate("MainInfoWindow", "Amps"))
        self.label_11.setText(_translate("MainInfoWindow", "Power"))
        self.label_9.setText(_translate("MainInfoWindow", "Voltage"))
        self.label_16.setText(_translate("MainInfoWindow", "Volts"))
        self.label_15.setText(_translate("MainInfoWindow", "Current"))
        self.label_19.setText(_translate("MainInfoWindow", "Power"))
        self.label_18.setText(_translate("MainInfoWindow", "Amps"))
        self.label_20.setText(_translate("MainInfoWindow", "Voltage"))
        self.label_17.setText(_translate("MainInfoWindow", "KW"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainInfoWindow = QtWidgets.QWidget()
    ui = Ui_MainInfoWindow()
    ui.setupUi(MainInfoWindow)
    MainInfoWindow.show()
    sys.exit(app.exec_())
