# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serialsetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Serial(object):
    def setupUi(self, Serial):
        Serial.setObjectName("Serial")
        Serial.setWindowModality(QtCore.Qt.ApplicationModal)
        Serial.setEnabled(True)
        Serial.resize(200, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Serial.sizePolicy().hasHeightForWidth())
        Serial.setSizePolicy(sizePolicy)
        Serial.setMinimumSize(QtCore.QSize(200, 350))
        Serial.setMaximumSize(QtCore.QSize(200, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/serial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Serial.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Serial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 336))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.baudratecomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.baudratecomboBox.setObjectName("baudratecomboBox")
        self.gridLayout.addWidget(self.baudratecomboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.descriptionplainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.descriptionplainTextEdit.setObjectName("descriptionplainTextEdit")
        self.gridLayout.addWidget(self.descriptionplainTextEdit, 6, 0, 1, 2)
        self.databitscomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.databitscomboBox.setObjectName("databitscomboBox")
        self.gridLayout.addWidget(self.databitscomboBox, 2, 1, 1, 1)
        self.stopbitscomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.stopbitscomboBox.setObjectName("stopbitscomboBox")
        self.gridLayout.addWidget(self.stopbitscomboBox, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.paritycomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.paritycomboBox.setEnabled(True)
        self.paritycomboBox.setObjectName("paritycomboBox")
        self.gridLayout.addWidget(self.paritycomboBox, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.portcomboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.portcomboBox.setObjectName("portcomboBox")
        self.gridLayout.addWidget(self.portcomboBox, 0, 1, 1, 1)
        self.okpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.okpushButton.setObjectName("okpushButton")
        self.gridLayout.addWidget(self.okpushButton, 8, 0, 1, 1)
        self.scanportpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.scanportpushButton.setObjectName("scanportpushButton")
        self.gridLayout.addWidget(self.scanportpushButton, 7, 0, 1, 2)
        self.cancelpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancelpushButton.setObjectName("cancelpushButton")
        self.gridLayout.addWidget(self.cancelpushButton, 8, 1, 1, 1)

        self.retranslateUi(Serial)
        QtCore.QMetaObject.connectSlotsByName(Serial)

    def retranslateUi(self, Serial):
        _translate = QtCore.QCoreApplication.translate
        Serial.setWindowTitle(_translate("Serial", "Serial Configuration"))
        self.label_3.setText(_translate("Serial", "Data Bits"))
        self.label_5.setText(_translate("Serial", "Stop Bits"))
        self.label.setText(_translate("Serial", "Port"))
        self.label_6.setText(_translate("Serial", "Description"))
        self.label_2.setText(_translate("Serial", "Baudrate"))
        self.label_4.setText(_translate("Serial", "Parity"))
        self.okpushButton.setText(_translate("Serial", "OK"))
        self.scanportpushButton.setText(_translate("Serial", "Scan Port"))
        self.cancelpushButton.setText(_translate("Serial", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Serial = QtWidgets.QWidget()
    ui = Ui_Serial()
    ui.setupUi(Serial)
    Serial.show()
    sys.exit(app.exec_())
